trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

variables:
  - group: sonarqube
  - group: sign
  - group: ossrh

resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates
      ref: fix/azure-pipeline-default-branch
      endpoint: bot

jobs:
  - template: azure/gradle/build.yml@templates
  - template: azure/gradle/create_tag_version.yml@templates
  - template: azure/gradle/upload_release.yml@templates
  - template: azure/gradle/upload_snapshot.yml@templates
